### ISSUE TITLE
Rect and line tools are broken

### ISSUE THREAD

**Issue by AV306** [AJR07-2/Paint-App#1]
## Problem:
When I use the line tool, the line is drawn but disappears. 
When I use the rectangle tool, nothing appears.

## Environment:
Windows 10 Home 20H2, Chromium Edge

#### Video:
https://user-images.githubusercontent.com/66512356/122200747-e88b6880-cecd-11eb-975f-fc03009551ea.mp4

**Comment by AJR07** [comment]
Thanks for mentioning the bug but I kinda already left this behind, so if I will probably only fix this when im bothered to do so, which  may be never, who knows? ;)

**Comment by AJR07** [comment]
Btw I went to test the rect tool it seems to work, im not sure im just guessing its inconsistent

**Comment by AJR07** [comment]
<img width="604" alt="image" src="https://user-images.githubusercontent.com/65659586/123544748-4a2dbb80-d787-11eb-9e93-092e13d3217a.png">

**Comment by AJR07** [comment]
The line tool definitely doesn't tho so yeah
